# Generated by Django 6.0.6 on 2026-07-03 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('condominios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='condominio',
            field=models.ForeignKey(blank=True, help_text='Condominio al que pertenece este usuario (no aplica a SUPERADMIN).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='condominios.condominio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(blank=True, help_text='Vinculo a su ficha del registro de copropietarios (obligatorio si rol=RESIDENTE).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_cuenta', to='condominios.persona'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
