# Generated by Django 6.0.6 on 2026-07-03 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('rut', models.CharField(blank=True, max_length=20, verbose_name='RUT administradora')),
                ('plazo_descargo_dias', models.PositiveSmallIntegerField(default=5, help_text='Dias corridos que tiene el residente para presentar descargos tras la notificacion.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='registros_importados/%Y/%m/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('filas_totales', models.PositiveIntegerField(default=0)),
                ('filas_ok', models.PositiveIntegerField(default=0)),
                ('filas_error', models.PositiveIntegerField(default=0)),
                ('detalle_errores', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('PROCESADO', 'Procesado'), ('CON_ERRORES', 'Procesado con errores'), ('FALLIDO', 'Fallido')], default='PROCESADO', max_length=20)),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to='condominios.condominio')),
            ],
            options={
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ej: Depto 302, Estacionamiento 12', max_length=50)),
                ('alicuota', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='condominios.condominio')),
            ],
            options={
                'ordering': ['identificador'],
                'unique_together': {('condominio', 'identificador')},
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_ocupacion', models.CharField(choices=[('PROPIETARIO', 'Propietario'), ('ARRENDATARIO', 'Arrendatario'), ('OCUPANTE', 'Ocupante')], max_length=20)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cedula_identidad', models.CharField(max_length=20)),
                ('domicilio', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='condominios.condominio')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='condominios.unidad')),
            ],
            options={
                'ordering': ['unidad__identificador', 'nombre_completo'],
                'indexes': [models.Index(fields=['condominio', 'cedula_identidad'], name='condominios_condomi_f03a66_idx')],
            },
        ),
    ]
