# Generated by Django 6.0.6 on 2026-07-03 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECLAMO', 'Reclamo'), ('SOLICITUD', 'Solicitud'), ('OBSERVACION', 'Observacion')], max_length=20)),
                ('texto', models.TextField()),
                ('plazo_respuesta_dias', models.PositiveSmallIntegerField(default=20)),
                ('fecha_limite_respuesta', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESPONDIDA', 'Respondida'), ('VENCIDA', 'Vencida (fuera de plazo legal)')], default='PENDIENTE', max_length=20)),
                ('respuesta_texto', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='condominios.condominio')),
                ('respondida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_respondidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='condominios.unidad')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
