# Generated by Django 6.0.6 on 2026-07-03 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_pdf', models.FileField(upload_to='reglamentos/%Y/%m/')),
                ('version', models.CharField(blank=True, max_length=50)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('texto_extraido', models.TextField(blank=True, help_text='Texto plano extraido del PDF (para la IA y busqueda).')),
                ('procesado_ia', models.BooleanField(default=False)),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglamentos', to='condominios.condominio')),
            ],
            options={
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='InfraccionCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500)),
                ('articulo_referencia', models.CharField(blank=True, max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad_monto', models.CharField(choices=[('CLP', 'Pesos chilenos'), ('UF', 'UF'), ('UTM', 'UTM')], default='UF', max_length=10)),
                ('gravedad', models.CharField(choices=[('LEVE', 'Leve'), ('GRAVE', 'Grave'), ('GRAVISIMA', 'Gravisima')], default='LEVE', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (sugerido por IA, sin confirmar)'), ('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='BORRADOR', max_length=20)),
                ('generado_por_ia', models.BooleanField(default=False)),
                ('texto_fuente', models.TextField(blank=True, help_text='Fragmento del reglamento usado por la IA para sugerir esta infraccion (trazabilidad).')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infracciones', to='condominios.condominio')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infracciones_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reglamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infracciones', to='reglamentos.reglamento')),
            ],
            options={
                'ordering': ['codigo'],
                'unique_together': {('condominio', 'codigo')},
            },
        ),
    ]
