# Generated by Django 6.0.6 on 2026-07-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraccioncatalogo',
            name='conlleva_contencion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infraccioncatalogo',
            name='plazo_ratificacion_horas',
            field=models.PositiveSmallIntegerField(default=24),
        ),
    ]
