# Generated by Django 6.0.6 on 2026-07-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglamentos', '0002_infraccioncatalogo_conlleva_contencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraccioncatalogo',
            name='quorum_ratificacion',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
