# Generated by Django 6.0.6 on 2026-07-23 17:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglamentos', '0003_infraccioncatalogo_quorum_ratificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraccioncatalogo',
            name='factor_reincidencia',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4),
        ),
    ]
