# Generated by Django 6.0.6 on 2026-08-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglamentos', '0004_infraccioncatalogo_factor_reincidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglamento',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reglamento',
            name='tipo',
            field=models.CharField(choices=[('REGLAMENTO_COPROPIEDAD', 'Reglamento de copropiedad'), ('ESTACIONAMIENTOS', 'Normas de uso de estacionamientos'), ('ESPACIOS_COMUNES', 'Normas de uso de espacios comunes'), ('SEGURIDAD', 'Normas de seguridad'), ('AMBIENTAL', 'Normativa ambiental'), ('ACTA_ASAMBLEA', 'Acta o acuerdo de asamblea'), ('OTRO', 'Otro cuerpo normativo')], default='REGLAMENTO_COPROPIEDAD', max_length=30),
        ),
        migrations.AddField(
            model_name='reglamento',
            name='titulo',
            field=models.CharField(blank=True, help_text='Como lo conoce la comunidad. Ej: "Instructivo de estacionamientos 2026".', max_length=200),
        ),
    ]
