# Generated by Django 6.0.6 on 2026-08-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglamentos', '0005_reglamento_fecha_documento_reglamento_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaTransversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LEY', 'Ley'), ('REGLAMENTO_LEY', 'Reglamento de la ley'), ('CIRCULAR_MINVU', 'Circular u ordinario MINVU'), ('DICTAMEN', 'Dictamen o jurisprudencia'), ('OTRA', 'Otra norma aplicable')], max_length=20)),
                ('identificador', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fuente_url', models.URLField(blank=True, help_text='Enlace oficial (bcn.cl, leychile.cl, minvu.cl) del que se obtuvo el texto.', max_length=500)),
                ('texto', models.TextField(blank=True, help_text='Texto oficial. Se carga con el comando cargar_normativa, no se escribe a mano.')),
                ('vigente', models.BooleanField(default=True)),
                ('resumen', models.TextField(blank=True, help_text='Sintesis de lo que esta norma exige, para usar cuando el texto completo no cabe.')),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Norma transversal',
                'verbose_name_plural': 'Normas transversales (Chile)',
                'ordering': ['identificador'],
            },
        ),
    ]
