# Generated by Django 6.0.6 on 2026-08-14 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglamentos', '0005_reglamento_fecha_documento_reglamento_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuenteNormativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LEY', 'Ley'), ('REGLAMENTO_LEY', 'Reglamento de la ley'), ('CIRCULAR_MINVU', 'Circular u ordinario MINVU'), ('CIRCULAR_SEC', 'Circular SEC'), ('DICTAMEN', 'Dictamen o jurisprudencia'), ('FOLLETO', 'Folleto o guia oficial'), ('OTRA', 'Otra fuente aplicable')], max_length=20)),
                ('identificador', models.CharField(help_text='Como se cita. Ej: "Ley 21.442", "Circular MINVU 15/2026".', max_length=120, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='normativa/%Y/%m/')),
                ('url_fuente', models.URLField(blank=True, max_length=500)),
                ('texto', models.TextField(blank=True, editable=False)),
                ('vigente', models.BooleanField(default=True, help_text='Al derogarse o reemplazarse, se desmarca. Sus fragmentos dejan de consultarse.')),
                ('nota_version', models.CharField(blank=True, help_text='Por que se cargo o actualizo. Ej: "Reemplaza la circular 8/2025".', max_length=300)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('indexada_en', models.DateTimeField(blank=True, null=True)),
                ('cargada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuentes_normativas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fuente normativa',
                'verbose_name_plural': 'Fuentes normativas (Chile)',
                'ordering': ['identificador'],
            },
        ),
        migrations.CreateModel(
            name='FragmentoNormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('referencia', models.CharField(help_text='Lo que se cita. Ej: "Art. 12". Nunca un indice interno.', max_length=100)),
                ('texto', models.TextField()),
                ('vector', models.BinaryField(blank=True, null=True)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragmentos', to='reglamentos.fuentenormativa')),
            ],
            options={
                'ordering': ['fuente_id', 'orden'],
                'unique_together': {('fuente', 'orden')},
            },
        ),
    ]
