# Generated by Django 6.0.6 on 2026-07-05 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(help_text='Ej: Copropiedad, Construccion, Seguridad Industrial', max_length=120)),
                ('vocabulario', models.JSONField(blank=True, default=dict, help_text='Diccionario de etiquetas para la UI. Ej: {"unidad": "Subcontratista", "multa": "No conformidad"}.')),
                ('marco_legal_nombre', models.CharField(default='Ley 21.442 sobre Copropiedad Inmobiliaria — Chile', max_length=200)),
                ('marco_legal_texto_notificacion', models.TextField(default='Documento generado conforme al procedimiento establecido en la Ley 21.442 sobre Copropiedad Inmobiliaria (Chile).', help_text='Parrafo legal que se estampa en el PDF de notificacion (determinista, sin IA).')),
                ('plazo_descargo_dias_default', models.PositiveSmallIntegerField(default=5)),
                ('plazo_ratificacion_horas_default', models.PositiveSmallIntegerField(default=24)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paquete de vertical',
                'verbose_name_plural': 'Paquetes de vertical',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CadenaEscalamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadenas_escalamiento', to='condominios.condominio')),
            ],
            options={
                'ordering': ['condominio_id', '-version'],
                'unique_together': {('condominio', 'version')},
            },
        ),
        migrations.AddField(
            model_name='condominio',
            name='vertical',
            field=models.ForeignKey(blank=True, help_text='Paquete de vertical al que se adhiere esta organizacion. Vacio = copropiedad (Ley 21.442).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizaciones', to='condominios.vertical'),
        ),
        migrations.CreateModel(
            name='NivelEscalamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(help_text='1 = primer notificado; el escalamiento sube de a uno.')),
                ('etiqueta', models.CharField(blank=True, help_text='Ej: "Jefatura de turno", "Gerencia".', max_length=100)),
                ('cadena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='condominios.cadenaescalamiento')),
                ('usuarios', models.ManyToManyField(related_name='niveles_escalamiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cadena_id', 'orden'],
                'unique_together': {('cadena', 'orden')},
            },
        ),
    ]
