# Generated by Django 6.0.6 on 2026-07-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0002_vertical_cadenaescalamiento_condominio_vertical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='codigo_comunidad',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
    ]
