# Generated by Django 6.0.6 on 2026-07-25 23:03

import secrets

from django.db import migrations


def asignar_codigos(apps, schema_editor):
    """Las comunidades existentes reciben su Codigo Unico de Comunidad."""
    Condominio = apps.get_model('condominios', 'Condominio')
    usados = set(
        Condominio.objects.exclude(codigo_comunidad__isnull=True)
        .values_list('codigo_comunidad', flat=True)
    )
    for condo in Condominio.objects.filter(codigo_comunidad__isnull=True):
        candidato = secrets.token_hex(4).upper()
        while candidato in usados:
            candidato = secrets.token_hex(4).upper()
        usados.add(candidato)
        condo.codigo_comunidad = candidato
        condo.save(update_fields=['codigo_comunidad'])


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0003_condominio_codigo_comunidad'),
    ]

    operations = [
        migrations.RunPython(asignar_codigos, migrations.RunPython.noop),
    ]
