# Generated by Django 6.0.6 on 2026-07-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0004_backfill_codigo_comunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='ventana_duplicados_horas',
            field=models.PositiveSmallIntegerField(default=24, help_text='Horas dentro de las cuales un nuevo reporte sobre la misma unidad se entiende referido al mismo hecho y se suma como corroboracion, en vez de abrir otro expediente (evita sancionar dos veces lo mismo).'),
        ),
    ]
