# Generated by Django 6.0.6 on 2026-07-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0005_condominio_ventana_duplicados_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='ultimo_resumen_enviado',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
