# Generated by Django 6.0.6 on 2026-07-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0006_condominio_ultimo_resumen_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='permanencia',
            field=models.CharField(choices=[('PERMANENTE', 'Permanente (reside 30 dias corridos o mas)'), ('TRANSITORIO', 'Transitorio (alojamiento temporal)')], default='PERMANENTE', help_text='Independiente del titulo: define si le aplican las restricciones a transitorios.', max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='vinculo_copropietario',
            field=models.CharField(blank=True, choices=[('', 'Sin vinculo declarado'), ('CONYUGE', 'Conyuge'), ('CONVIVIENTE_CIVIL', 'Conviviente civil'), ('FAMILIAR', 'Otro familiar')], default='', help_text='Conyuge o conviviente civil pueden integrar el Comite aunque no sean dueños.', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rol_ocupacion',
            field=models.CharField(choices=[('PROPIETARIO', 'Propietario'), ('ARRENDATARIO', 'Arrendatario'), ('USUFRUCTUARIO', 'Usufructuario'), ('COMODATARIO', 'Comodatario (uso gratuito)'), ('OCUPANTE', 'Ocupante a otro titulo')], max_length=20),
        ),
    ]
