# Generated by Django 6.0.6 on 2026-08-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0007_persona_permanencia_persona_vinculo_copropietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='condicion_especial',
            field=models.CharField(blank=True, choices=[('', 'Sin condicion declarada'), ('FALLECIDO', 'Fallecido'), ('DISCAPACIDAD', 'Situacion de discapacidad'), ('REQUIERE_APOYO', 'Requiere apoyo para tramites digitales')], default='', help_text='Detiene el cobro automatico para que alguien revise el caso antes.', max_length=20),
        ),
    ]
