# Generated by Django 6.0.6 on 2026-08-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0008_persona_condicion_especial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='plazo_resolucion_dias',
            field=models.PositiveSmallIntegerField(default=15, help_text='Dias corridos que tiene el Comite para resolver una apelacion presentada.'),
        ),
    ]
