# Generated by Django 6.0.6 on 2026-08-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0009_condominio_plazo_resolucion_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='quorum_resolucion_apelacion',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cuantos miembros del Comite deben coincidir para resolver una apelacion.'),
        ),
    ]
