# Generated by Django 6.0.6 on 2026-08-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0010_condominio_quorum_resolucion_apelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='cortesias_antes_de_multar',
            field=models.PositiveSmallIntegerField(default=2, help_text='Cuantas faltas NO graves se avisan sin cobro antes de empezar a multar. 0 = se multa desde la primera.'),
        ),
    ]
