# Generated by Django 6.0.6 on 2026-07-03 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        ('multas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato AAAA-MM', max_length=7)),
                ('archivo_csv', models.FileField(blank=True, null=True, upload_to='gastos_comunes/%Y/%m/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('total_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_exportacion', to='condominios.condominio')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_generacion'],
                'unique_together': {('condominio', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='CargoGastoComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=255)),
                ('multa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_gasto_comun', to='multas.multa')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_gastos_comunes', to='condominios.unidad')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='gastos_comunes.loteexportacion')),
            ],
        ),
    ]
