# Generated by Django 6.0.6 on 2026-07-25 23:02

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('condominios', '0003_condominio_codigo_comunidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('FISCALIZADOR', 'Fiscalizador (Conserje)'), ('COMITE', 'Comite de Administracion'), ('ADMINISTRADOR', 'Administrador'), ('RESIDENTE', 'Residente'), ('SUPERADMIN', 'Administrador del sistema'), ('PENDIENTE', 'Pendiente de asignacion')], max_length=20),
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('rol_sugerido', models.CharField(choices=[('FISCALIZADOR', 'Fiscalizador (Conserje)'), ('COMITE', 'Comite de Administracion'), ('ADMINISTRADOR', 'Administrador'), ('RESIDENTE', 'Residente'), ('SUPERADMIN', 'Administrador del sistema'), ('PENDIENTE', 'Pendiente de asignacion')], max_length=20)),
                ('codigo', models.CharField(default=accounts.models._generar_codigo_invitacion, max_length=32, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('REVOCADA', 'Revocada')], default='PENDIENTE', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('aceptada_en', models.DateTimeField(blank=True, null=True)),
                ('aceptada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_aceptadas', to=settings.AUTH_USER_MODEL)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='condominios.condominio')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones', to='condominios.unidad')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
    ]
