# Generated by Django 6.0.6 on 2026-07-03 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
        ('multas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='persona_reportada',
            field=models.ForeignKey(blank=True, help_text='Persona de la unidad senalada como presunta infractora (el Comite confirma al aprobar).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_reportado', to='condominios.persona'),
        ),
    ]
