# Generated by Django 6.0.6 on 2026-07-05 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0002_ticket_persona_reportada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciafoto',
            name='anclaje_fisico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidenciafoto',
            name='metadatos_origen',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evidenciafoto',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='ActaSellada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField()),
                ('tipo_acto', models.CharField(choices=[('APROBACION', 'Aprobacion de la multa'), ('RECHAZO', 'Rechazo del reporte'), ('NOTIFICACION', 'Notificacion al residente'), ('DESCARGO_PRESENTADO', 'Descargo presentado'), ('RESOLUCION_DESCARGO', 'Resolucion del descargo'), ('FIRMEZA_AUTOMATICA', 'Firmeza automatica por vencimiento de plazo')], max_length=30)),
                ('auth_metodo', models.CharField(default='jwt_password_session', max_length=40)),
                ('ts', models.DateTimeField()),
                ('manifiesto', models.JSONField()),
                ('manifiesto_sha256', models.CharField(max_length=64)),
                ('hash_previo', models.CharField(max_length=64)),
                ('hash_acto', models.CharField(db_index=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_selladas', to='multas.multa')),
            ],
            options={
                'ordering': ['multa_id', 'indice'],
                'unique_together': {('multa', 'indice')},
            },
        ),
    ]
