# Generated by Django 6.0.6 on 2026-07-05 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0004_actasellada_triggers_inmutabilidad'),
        ('reglamentos', '0002_infraccioncatalogo_conlleva_contencion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actasellada',
            name='tipo_acto',
            field=models.CharField(choices=[('APROBACION', 'Aprobacion de la multa'), ('RECHAZO', 'Rechazo del reporte'), ('NOTIFICACION', 'Notificacion al residente'), ('DESCARGO_PRESENTADO', 'Descargo presentado'), ('RESOLUCION_DESCARGO', 'Resolucion del descargo'), ('FIRMEZA_AUTOMATICA', 'Firmeza automatica por vencimiento de plazo'), ('CONTENCION_EJECUTADA', 'Medida inmediata ejecutada'), ('CONTENCION_RATIFICADA', 'Medida inmediata ratificada'), ('CONTENCION_LEVANTADA', 'Medida inmediata levantada'), ('ESCALAMIENTO_POR_OMISION', 'Escalamiento por omision de ratificacion')], max_length=30),
        ),
        migrations.CreateModel(
            name='MedidaInmediata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('estado', models.CharField(choices=[('EJECUTADA', 'Ejecutada (contencion activa, pendiente de ratificacion)'), ('RATIFICADA', 'Ratificada (contencion activa, con dueño)'), ('EN_ESCALAMIENTO', 'En escalamiento por omision (contencion ACTIVA)'), ('LEVANTADA', 'Levantada por acto humano')], default='EJECUTADA', max_length=20)),
                ('auth_metodo_ejecucion', models.CharField(default='jwt_password_session', max_length=40)),
                ('ejecutada_en', models.DateTimeField()),
                ('plazo_ratificacion_horas', models.PositiveSmallIntegerField()),
                ('proxima_revision', models.DateTimeField(db_index=True)),
                ('nivel_escalamiento', models.PositiveSmallIntegerField(default=0)),
                ('ratificada_en', models.DateTimeField(blank=True, null=True)),
                ('levantada_en', models.DateTimeField(blank=True, null=True)),
                ('causal_levantamiento', models.CharField(blank=True, choices=[('CORREGIDA', 'Hallazgo corregido (con evidencia)'), ('DESESTIMADA', 'Hallazgo desestimado (con fundamento)')], max_length=20)),
                ('fundamento_levantamiento', models.TextField(blank=True)),
                ('ejecutada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas_ejecutadas', to=settings.AUTH_USER_MODEL)),
                ('evidencias', models.ManyToManyField(blank=True, related_name='medidas_inmediatas', to='multas.evidenciafoto')),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medidas_inmediatas', to='reglamentos.infraccioncatalogo')),
                ('levantada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas_levantadas', to=settings.AUTH_USER_MODEL)),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medidas_inmediatas', to='multas.multa')),
                ('ratificada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas_ratificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ejecutada_en'],
            },
        ),
    ]
