# Generated by Django 6.0.6 on 2026-07-03 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominios', '0001_initial'),
        ('reglamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('EN_REVISION', 'En revision del Comite'), ('RECHAZADA', 'Rechazada por el Comite'), ('APROBADA', 'Aprobada, pendiente de notificacion'), ('NOTIFICADA', 'Notificada al residente'), ('CON_DESCARGO', 'Con descargo presentado'), ('FIRME', 'Firme (sin apelaciones pendientes)'), ('ANULADA', 'Anulada'), ('EXPORTADA', 'Exportada a gastos comunes')], default='EN_REVISION', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('pdf_notificacion', models.FileField(blank=True, null=True, upload_to='notificaciones/%Y/%m/')),
                ('plazo_descargo_dias', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_limite_descargo', models.DateTimeField(blank=True, null=True)),
                ('es_reincidencia', models.BooleanField(default=False)),
                ('agravante_sugerido', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_firme', models.DateTimeField(blank=True, null=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='condominios.condominio')),
                ('infraccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multas', to='reglamentos.infraccioncatalogo')),
                ('multa_primera_sancion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reincidencias', to='multas.multa')),
                ('notificada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas_notificadas', to=settings.AUTH_USER_MODEL)),
                ('persona_infractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multas', to='condominios.persona')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='condominios.unidad')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='multas.multa')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Descargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='descargos/%Y/%m/')),
                ('fecha_presentacion', models.DateTimeField(auto_now_add=True)),
                ('resolucion', models.CharField(choices=[('PENDIENTE', 'Pendiente de resolucion'), ('ACEPTADO', 'Aceptado (multa anulada)'), ('RECHAZADO', 'Rechazado (multa se mantiene firme)')], default='PENDIENTE', max_length=20)),
                ('comentario_resolucion', models.TextField(blank=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('presentado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descargos_resueltos', to=settings.AUTH_USER_MODEL)),
                ('multa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descargo', to='multas.multa')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_hecho', models.DateTimeField(help_text='Fecha/hora en que ocurrio la presunta infraccion.')),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revision'), ('CONVERTIDO', 'Convertido en multa'), ('DESCARTADO', 'Descartado por el Comite')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='condominios.condominio')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='condominios.unidad')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='multa',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multa', to='multas.ticket'),
        ),
        migrations.CreateModel(
            name='EvidenciaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evidencias/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='multas.ticket')),
            ],
        ),
    ]
