# Generated by Django 6.0.6 on 2026-07-06 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0002_vertical_cadenaescalamiento_condominio_vertical_and_more'),
        ('multas', '0005_alter_actasellada_tipo_acto_medidainmediata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medidainmediata',
            name='quorum_requerido',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='actasellada',
            name='tipo_acto',
            field=models.CharField(choices=[('APROBACION', 'Aprobacion de la multa'), ('RECHAZO', 'Rechazo del reporte'), ('NOTIFICACION', 'Notificacion al residente'), ('DESCARGO_PRESENTADO', 'Descargo presentado'), ('RESOLUCION_DESCARGO', 'Resolucion del descargo'), ('FIRMEZA_AUTOMATICA', 'Firmeza automatica por vencimiento de plazo'), ('CONTENCION_EJECUTADA', 'Medida inmediata ejecutada'), ('VOTO_RATIFICACION', 'Voto de ratificacion (quorum)'), ('CONTENCION_RATIFICADA', 'Medida inmediata ratificada'), ('CONTENCION_LEVANTADA', 'Medida inmediata levantada'), ('ESCALAMIENTO_POR_OMISION', 'Escalamiento por omision de ratificacion')], max_length=30),
        ),
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('acciones', models.JSONField(default=list)),
                ('tope_gravedad', models.CharField(default='GRAVE', max_length=20)),
                ('vigencia_desde', models.DateTimeField()),
                ('vigencia_hasta', models.DateTimeField()),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('REVOCADA', 'Revocada')], default='VIGENTE', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('otorgamiento_hash', models.CharField(editable=False, max_length=64)),
                ('revocada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegaciones', to='condominios.condominio')),
                ('delegado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('delegante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegaciones_otorgadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='VotoRatificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_calidad_de', models.CharField(choices=[('TITULAR', 'Titular (cargo propio)'), ('DELEGADO', 'Delegado')], max_length=20)),
                ('ts', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos_ratificacion', to=settings.AUTH_USER_MODEL)),
                ('delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votos_emitidos', to='multas.delegacion')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='multas.medidainmediata')),
            ],
            options={
                'ordering': ['medida_id', 'ts'],
                'unique_together': {('medida', 'actor')},
            },
        ),
    ]
