# Generated by Django 6.0.6 on 2026-07-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0006_medidainmediata_quorum_requerido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descargo',
            name='monto_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de la multa antes del descuento, congelado al resolver (trazabilidad).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='descargo',
            name='porcentaje_descuento',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rebaja porcentual aplicada al monto cuando la resolucion es DESCUENTO (ej: 30, 50).', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='descargo',
            name='resolucion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de resolucion'), ('ACEPTADO', 'Aceptado (multa anulada)'), ('RECHAZADO', 'Rechazado (multa se mantiene firme)'), ('DESCUENTO', 'Descuento parcial (firme, con el monto rebajado)')], default='PENDIENTE', max_length=20),
        ),
    ]
