# Generated by Django 6.0.6 on 2026-07-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0007_descargo_monto_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='propuesta_confianza',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='multa',
            name='propuesta_fundamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='multa',
            name='propuesta_origen',
            field=models.CharField(blank=True, help_text='IA = clasificador; COINCIDENCIA = respaldo por terminos; vacio = sin propuesta.', max_length=20),
        ),
    ]
