# Generated by Django 6.0.6 on 2026-07-27 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0008_multa_propuesta_confianza_multa_propuesta_fundamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='corrobora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corroboraciones', to='multas.multa'),
        ),
    ]
