# Generated by Django 6.0.6 on 2026-08-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0009_ticket_corrobora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de revision'), ('CONVERTIDO', 'Convertido en multa')], default='PENDIENTE', max_length=20),
        ),
    ]
