# Generated by Django 6.0.6 on 2026-08-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0010_alter_ticket_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actasellada',
            name='tipo_acto',
            field=models.CharField(choices=[('CURSE_AUTOMATICO', 'Curse automatico de la multa (sin filtro previo)'), ('APROBACION', 'Aprobacion de la multa'), ('RECHAZO', 'Rechazo del reporte'), ('NOTIFICACION', 'Notificacion al residente'), ('DESCARGO_PRESENTADO', 'Descargo presentado'), ('RESOLUCION_DESCARGO', 'Resolucion del descargo'), ('FIRMEZA_AUTOMATICA', 'Firmeza automatica por vencimiento de plazo'), ('CONTENCION_EJECUTADA', 'Medida inmediata ejecutada'), ('VOTO_RATIFICACION', 'Voto de ratificacion (quorum)'), ('CONTENCION_RATIFICADA', 'Medida inmediata ratificada'), ('CONTENCION_LEVANTADA', 'Medida inmediata levantada'), ('ESCALAMIENTO_POR_OMISION', 'Escalamiento por omision de ratificacion')], max_length=30),
        ),
    ]
