# Generated by Django 6.0.6 on 2026-08-14 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0011_alter_actasellada_tipo_acto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='canal_acuse',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='multa',
            name='fecha_acuse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actasellada',
            name='tipo_acto',
            field=models.CharField(choices=[('CURSE_AUTOMATICO', 'Curse automatico de la multa (sin filtro previo)'), ('APROBACION', 'Aprobacion de la multa'), ('RECHAZO', 'Rechazo del reporte'), ('NOTIFICACION', 'Notificacion al residente'), ('DESCARGO_PRESENTADO', 'Descargo presentado'), ('ACUSE_RECIBO', 'Acuse de recibo de la notificacion'), ('RESOLUCION_DESCARGO', 'Resolucion del descargo'), ('FIRMEZA_AUTOMATICA', 'Firmeza automatica por vencimiento de plazo'), ('CONTENCION_EJECUTADA', 'Medida inmediata ejecutada'), ('VOTO_RATIFICACION', 'Voto de ratificacion (quorum)'), ('CONTENCION_RATIFICADA', 'Medida inmediata ratificada'), ('CONTENCION_LEVANTADA', 'Medida inmediata levantada'), ('ESCALAMIENTO_POR_OMISION', 'Escalamiento por omision de ratificacion')], max_length=30),
        ),
        migrations.CreateModel(
            name='EntregaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('EMAIL', 'Correo electronico'), ('WHATSAPP', 'WhatsApp'), ('TELEFONO', 'Llamada telefonica'), ('PRESENCIAL', 'Entrega en mano'), ('BUZON', 'Constancia dejada en el buzon de la unidad')], max_length=20)),
                ('destino', models.CharField(max_length=200)),
                ('intento', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada, sin acuse todavia'), ('FALLIDA', 'El envio fallo'), ('ACUSADA', 'Recepcion acusada por el destinatario')], default='ENVIADA', max_length=20)),
                ('enviada_en', models.DateTimeField(auto_now_add=True)),
                ('acusada_en', models.DateTimeField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, help_text='Error del envio o nota de quien entrego.')),
                ('multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='multas.multa')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['enviada_en'],
            },
        ),
    ]
