# Generated by Django 6.0.6 on 2026-08-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0012_multa_canal_acuse_multa_fecha_acuse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreganotificacion',
            name='canal',
            field=models.CharField(choices=[('EMAIL', 'Correo electronico'), ('WHATSAPP', 'WhatsApp'), ('APP', 'Ingreso a la aplicacion'), ('TELEFONO', 'Llamada telefonica'), ('PRESENCIAL', 'Entrega en mano'), ('BUZON', 'Constancia dejada en el buzon de la unidad')], max_length=20),
        ),
    ]
