# Generated by Django 6.0.6 on 2026-08-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0013_alter_entreganotificacion_canal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descargo',
            name='resolucion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de resolucion'), ('ACEPTADO', 'Aceptado (multa anulada)'), ('RECHAZADO', 'Rechazado (multa se mantiene firme)'), ('DESCUENTO', 'Descuento parcial (firme, con el monto rebajado)'), ('CORTESIA', 'Parte de cortesia (falta acreditada, sin cobro)')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='multa',
            name='estado',
            field=models.CharField(choices=[('EN_REVISION', 'En revision del Comite'), ('RECHAZADA', 'Rechazada por el Comite'), ('APROBADA', 'Aprobada, pendiente de notificacion'), ('NOTIFICADA', 'Notificada al residente'), ('CON_DESCARGO', 'Con descargo presentado'), ('FIRME', 'Firme (sin apelaciones pendientes)'), ('CORTESIA', 'Parte de cortesia (sin cobro)'), ('ANULADA', 'Anulada'), ('EXPORTADA', 'Exportada a gastos comunes')], default='EN_REVISION', max_length=20),
        ),
    ]
