# Generated by Django 6.0.6 on 2026-08-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0014_alter_descargo_resolucion_alter_multa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actasellada',
            name='tipo_acto',
            field=models.CharField(choices=[('CURSE_AUTOMATICO', 'Curse automatico de la multa (sin filtro previo)'), ('APROBACION', 'Aprobacion de la multa'), ('RECHAZO', 'Rechazo del reporte'), ('NOTIFICACION', 'Notificacion al residente'), ('DESCARGO_PRESENTADO', 'Descargo presentado'), ('ACUSE_RECIBO', 'Acuse de recibo de la notificacion'), ('RESOLUCION_DESCARGO', 'Resolucion del descargo'), ('FIRMEZA_AUTOMATICA', 'Firmeza automatica por vencimiento de plazo'), ('CONFIRMACION_PREVIA_COBRO', 'Confirmacion antes del cobro'), ('CONTENCION_EJECUTADA', 'Medida inmediata ejecutada'), ('VOTO_RATIFICACION', 'Voto de ratificacion (quorum)'), ('CONTENCION_RATIFICADA', 'Medida inmediata ratificada'), ('CONTENCION_LEVANTADA', 'Medida inmediata levantada'), ('ESCALAMIENTO_POR_OMISION', 'Escalamiento por omision de ratificacion')], max_length=30),
        ),
        migrations.AlterField(
            model_name='multa',
            name='estado',
            field=models.CharField(choices=[('EN_REVISION', 'En revision del Comite'), ('RECHAZADA', 'Rechazada por el Comite'), ('APROBADA', 'Aprobada, pendiente de notificacion'), ('NOTIFICADA', 'Notificada al residente'), ('CON_DESCARGO', 'Con descargo presentado'), ('POR_CONFIRMAR', 'Por confirmar antes del cobro'), ('FIRME', 'Firme (sin apelaciones pendientes)'), ('CORTESIA', 'Parte de cortesia (sin cobro)'), ('ANULADA', 'Anulada'), ('EXPORTADA', 'Exportada a gastos comunes')], default='EN_REVISION', max_length=20),
        ),
    ]
