# Generated by Django 6.0.6 on 2026-08-14 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0015_alter_actasellada_tipo_acto_alter_multa_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='descargo',
            name='fecha_limite_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actasellada',
            name='tipo_acto',
            field=models.CharField(choices=[('CURSE_AUTOMATICO', 'Curse automatico de la multa (sin filtro previo)'), ('APROBACION', 'Aprobacion de la multa'), ('RECHAZO', 'Rechazo del reporte'), ('NOTIFICACION', 'Notificacion al residente'), ('DESCARGO_PRESENTADO', 'Descargo presentado'), ('ACUSE_RECIBO', 'Acuse de recibo de la notificacion'), ('ANTECEDENTE_APORTADO', 'Antecedente sumado a la apelacion'), ('RESOLUCION_DESCARGO', 'Resolucion del descargo'), ('FIRMEZA_AUTOMATICA', 'Firmeza automatica por vencimiento de plazo'), ('CONFIRMACION_PREVIA_COBRO', 'Confirmacion antes del cobro'), ('CONTENCION_EJECUTADA', 'Medida inmediata ejecutada'), ('VOTO_RATIFICACION', 'Voto de ratificacion (quorum)'), ('CONTENCION_RATIFICADA', 'Medida inmediata ratificada'), ('CONTENCION_LEVANTADA', 'Medida inmediata levantada'), ('ESCALAMIENTO_POR_OMISION', 'Escalamiento por omision de ratificacion')], max_length=30),
        ),
        migrations.CreateModel(
            name='AntecedenteDescargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='antecedentes/%Y/%m/')),
                ('origen', models.CharField(choices=[('RESIDENTE', 'Aportado por el residente'), ('REUNION', 'Aportado en la reunion')], default='RESIDENTE', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('descargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='multas.descargo')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
