# Generated by Django 6.0.6 on 2026-08-14 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0016_descargo_fecha_limite_resolucion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actasellada',
            name='tipo_acto',
            field=models.CharField(choices=[('CURSE_AUTOMATICO', 'Curse automatico de la multa (sin filtro previo)'), ('APROBACION', 'Aprobacion de la multa'), ('RECHAZO', 'Rechazo del reporte'), ('NOTIFICACION', 'Notificacion al residente'), ('DESCARGO_PRESENTADO', 'Descargo presentado'), ('ACUSE_RECIBO', 'Acuse de recibo de la notificacion'), ('ANTECEDENTE_APORTADO', 'Antecedente sumado a la apelacion'), ('REUNION_CONVOCADA', 'Reunion convocada con el residente'), ('REUNION_REALIZADA', 'Reunion realizada'), ('VOTO_RESOLUCION', 'Voto del Comite sobre la apelacion'), ('RESOLUCION_DESCARGO', 'Resolucion del descargo'), ('FIRMEZA_AUTOMATICA', 'Firmeza automatica por vencimiento de plazo'), ('CONFIRMACION_PREVIA_COBRO', 'Confirmacion antes del cobro'), ('CONTENCION_EJECUTADA', 'Medida inmediata ejecutada'), ('VOTO_RATIFICACION', 'Voto de ratificacion (quorum)'), ('CONTENCION_RATIFICADA', 'Medida inmediata ratificada'), ('CONTENCION_LEVANTADA', 'Medida inmediata levantada'), ('ESCALAMIENTO_POR_OMISION', 'Escalamiento por omision de ratificacion')], max_length=30),
        ),
        migrations.CreateModel(
            name='ReunionApelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('ONLINE', 'En linea'), ('PRESENCIAL', 'Presencial')], max_length=20)),
                ('fecha_propuesta', models.DateTimeField()),
                ('lugar_o_enlace', models.CharField(max_length=300)),
                ('estado', models.CharField(choices=[('PROPUESTA', 'Propuesta, esperando al residente'), ('CONFIRMADA', 'Confirmada por el residente'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PROPUESTA', max_length=20)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('acta', models.TextField(blank=True, help_text='Lo que se expuso en la reunion.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('convocada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reuniones_convocadas', to=settings.AUTH_USER_MODEL)),
                ('descargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='multas.descargo')),
            ],
            options={
                'ordering': ['fecha_propuesta'],
            },
        ),
        migrations.CreateModel(
            name='VotoResolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(choices=[('PENDIENTE', 'Pendiente de resolucion'), ('ACEPTADO', 'Aceptado (multa anulada)'), ('RECHAZADO', 'Rechazado (multa se mantiene firme)'), ('DESCUENTO', 'Descuento parcial (firme, con el monto rebajado)'), ('CORTESIA', 'Parte de cortesia (falta acreditada, sin cobro)')], max_length=20)),
                ('porcentaje_descuento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('descargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='multas.descargo')),
            ],
            options={
                'ordering': ['ts'],
                'unique_together': {('descargo', 'actor')},
            },
        ),
    ]
