# Generated by Django 6.0.6 on 2026-08-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0017_alter_actasellada_tipo_acto_reunionapelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciafoto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/video/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='evidenciafoto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/%Y/%m/'),
        ),
    ]
