# Generated by Django 6.0.6 on 2026-08-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0018_evidenciafoto_video_alter_evidenciafoto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='monto_sin_cortesia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
