# Generated by Django 6.0.6 on 2026-08-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0019_multa_monto_sin_cortesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='analisis_evidencia',
            field=models.TextField(blank=True),
        ),
    ]
